>The mortar fire has been shelling your outpost for an hour or so
>You’ve had to take shelter in a shabby section of the storage room
>Eventually, the Shelling stops, and you run out to open area
>Rush towards the armory, hoping it wasn’t to heavily damaged 
>But the sound of sniper fire taking potshots  at anyone who stands still
>Manage to reach the armory door
>But a sniper round goes through the tarsus of your right foot
>Suddenly fall to the floor in agonizing pain 
>Hear the sounds of Humvee’s and APC wheels
>One Humvee has its M2 pointed at you, manned by a golden jackal in desert gear
>Its doors open, four soldiers of the state bolt out
>One of them, a Dingo, put the barrel of her SOPMOD FN SCAR rifle on the back of your head
>”Today’s my lucky day, I get a shiny medal and see myself on tv.”
>She suddenly pulls out a camera or video recorder 
>”And I get to keep you under ‘rehabilitation’ rights.”
>She forces you onto your feet, the falcon combat medic motioning her to a makeshift hospital bed
>”Bleeding’s pretty intense, we’ll have to send him to a hospital to treat that gnarly wound, Sniper gals must be proud of themselves.”
>She grabs a syringe labeled “Transport sedative”
>Feel it enter your right shoulder
>”You’ll feel woozy when you wake up, but for now, try to get some rest”
>Fell your eyes get heavy, the last thing you hear is to load you up alongside the other men
>When you wake up, you’re in the cold antiseptic scented room of a military hospital
>Hear the door open, showing the dingo and a well dressed tiger officer
>Try to move your arm, only to notice you’ve been cuffed to the bed
>”What the fuck do you want from me?” You groggily ask
>”Names of the other cells in your division, counter-intel, Covert operations, anything.” 
>”You really expect me to just tell you? I’m not of those so called “Humies” who decided to stab their nation and species in the back in the name of getting some tail.”
>The tiger looks mildly disappointed, but her face indicates this is not her first rodeo
>”Should you willingly give up any intelligence on military operations, the state will issue a full pardon for any crimes committed during your time in the insurrection.”
>”And then what? State puts on a little show and dance, I grovel on my knees begging for forgiveness, then the next thing I know, I’m married to that 30-something year old she-beast?”
>The dingo suddenly forced your injured foot, now in a cast, downward
>You all but screamed from the pain, even when she let go, it was still agonizing
>”We don’t appreciate the use of such a language.”
>”Should you refuse, you will be sent to a holding cell in a prison in the Siberia district.”
>”And trust me, it ain’t gonna be the ritz, all those bears and snow leopards? they haven’t been able to get off in quite some time.”
>”I can see it now, you in that cute little prison garb, being watch by several pent up guards, looking at you like a raw cut of meat.”
>”Maybe it’ll be commissar Aleksándra, she’s always appreciated the tough to crack individuals”
>”And once you’re broken by her, all the guards will know your a free use slut.”
>”So I’ll ask one last time, will you reveal some information, and the state will provide you with a pardon, do you understand?”
>”Yes…Ma’am.”
>The officer lets out a smug smile of satisfaction
>”Thats what I’d like to hear, once you are discharged, we will talk more.”
>Both of them exit the hospital room, leaving you with your thoughts
>”Damn, I can see why some people defected.”
